export enum TransactionMethod {
  CASH = 'CASH',
  PIX = 'PIX',
  DEBIT_CARD = 'DEBIT_CARD',
  CREDIT_CARD = 'CREDIT_CARD',
  BANK_SLIP = 'BANK_SLIP',
  BANK_TRANSFER = 'BANK_TRANSFER',
  AUTOMATIC_DEBIT = 'AUTOMATIC_DEBIT',
  CRYPTO = 'CRYPTO',
  OTHERS = 'OTHERS'
}
